main: com.rayzr522.requestit.RequestIt
name: RequestIt
version: 1.0.0
description: A plugin to request new features for the server.
author: Rayzr
#depend: [CreativelyNamedLib]
#commands:
#  requestit:
#    description: RequestIt main command
#    aliases: [alias1,alias2]
#    usage: "/requestit [command]"
#    permission: RequestIt.main
