main: com.rayzr522.requestit.RequestIt
name: RequestIt
version: 1.0.0
description: A plugin to request new features for the server.
author: Rayzr
depend: [CreativelyNamedLib]
commands:
  request:
    description: RequestIt main command
    usage: "/request [view [id]]|<message>"
